name: DMI_bot_deploy

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "docs/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies for requirements and testing
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with pylint
        run: |
          pylint main.py setup.py module
      # - name: Setup enviroment
      #   run: |
      #     mv config/settings.yaml.dist config/settings.yaml
      #     mv data/DMI_DB.db.dist data/DMI_DB.db
      #     python3 setup.py useless_token --test_api_id ${{secrets.API_ID}} \
      #     --test_api_hash ${{secrets.API_HASH}} --test_session ${{secrets.SESSION}} \
      #     --test_tag ${{secrets.TEST_TAG}} --test_token ${{secrets.TEST_TOKEN}} \
      #     --test_representatives_group ${{secrets.TEST_USER_ID}} --test_dev_group_chatid ${{secrets.TEST_USER_ID}}
      - name: Unit test
        run: pytest tests/unit/
      # - name: End-to-end test
      #   run: pytest tests/e2e/
